### ISSUE TITLE
2.1 displays views that should stay hidden

### ISSUE THREAD

**Issue by jbblanchet** [BlueSpire/Durandal#540]
It's sometimes useful to use composition to include html that should stay hidden. 2 scenarios where we use it:
- Include some html whose visibility is controlled externally (i.e. by a parent component).
- Include svg definitions in the DOM (since external file loading support is broken in current browsers).

Pull request  #520 broke that by forcing visibility to block when it was none. If it was 'none' before the hide, it should stay 'none' after.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
