### ISSUE TITLE
Infinite activation/binding loop after navigating away then back

### ISSUE THREAD

**Issue by ghost** [BlueSpire/Durandal#553]
This issue seems to be specific to version 2.1.0. If start from Page A then navigate to Page B then back to Page A, it triggers an endless loop of activating and binding.
![Infinite loop console logs](https://cloud.githubusercontent.com/assets/1906692/3473258/e3d004ac-02d5-11e4-984c-2315c7765ced.png)

If I replace viewEngine.js v2.1.0 with viewEngine.js v2.0.1, the endless loop is gone but the double activation happens. 

![Double activation console logs](https://cloud.githubusercontent.com/assets/1906692/3473306/9b401c1c-02d6-11e4-93ba-786e0ed643df.png)

**Comment by davismj** [comment]
If you could provide a gist or git repo demonstrating the problem that would help me resolve it.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
