### ISSUE TITLE
ViewEngine caching problem

### ISSUE THREAD

**Issue by omniscient** [BlueSpire/Durandal#558]
I know this is going to be pretty vague of an issue but after spending 4 hours on the phone with my buddy working through this bug, I don't really feel like trying to put an example together at the moment. Maybe its unnecessary and you can think of a way to reproduce this.

Basically, we had to comment line 166 of viewEngine.js for our view to work several times in a row: // that.putViewInCache(requirePath, element);

We couldn't understand exactly why this was happening but basically, when we re-open the same view (twice in a row), when the first property change on that view occurs it eventually triggers a dispose on the view that eventually forces a Router binding update which wrecks havoc because the router goes through the composition lifecycle when it shouldn't

If you are interested in understanding what is going on, I could do a quick screen share with you. If not, I can try to put an example together, but that might take a while.

By the way, awesome work on the framework!

**Comment by PWKad** [comment]
@twill88 @omniscient @agmonks - Does anyone have a repo that this can be repro'd in?

**Comment by davismj** [comment]
Just following up with this issue. Does anyone have a demo repo?

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
