### ISSUE TITLE
When canDeactivate returns false it does not remove the cancelled route from the router breadcrumb

### ISSUE THREAD

**Issue by omniscient** [BlueSpire/Durandal#559]
Our viewmodels includes the canDeactivate method such that we can prevent users from navigating away while they have unsaved changed in our SPA. The sequence goes like this:
1. Browse to /consumer
2. Browse to /consumer/assessment
3. Modify the record
4. Try to browse to /Search by clicking a button in the app
5. Answer cancel on dialog to stop navigation that presents such that canDeactivate returns false
6. User is still on /consumer/assessment
7. Click close which forces the router to navigateback()
8. Answer save on dialog such that canDeactivate returns true
9. Router sends user to /Search

Expected result:
User should go back to /consumer/assessment which is the last view they were on.

**Comment by davismj** [comment]
Excellent. I will review.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
