### ISSUE TITLE
No errorhandling if module is a function and resolveObject fails

### ISSUE THREAD

**Issue by mokkabonna** [BlueSpire/Durandal#560]
In https://github.com/BlueSpire/Durandal/pull/546 cancellation of the navigation was added if the module loading failed. This works fine if we have the following module: 

```
define(function(){
    return {
        foo: doesNotExist.property
    };
});
```

It will then complain that doesNotExist is undefined and you can't access it's property. This is because the error ocures during the loading of the module.

However if the module loads fine, but the resolution of the object, or anything in the `then` handler https://github.com/BlueSpire/Durandal/blob/Next-Version/src/plugins/js/router.js#L423 goes wrong, then the fail will not get triggered. 

This will happen if the module looks like this:

```
define(function(){
    return function(){
        this.foo = doesNotExist.property;
    };
});
```

When `system.resolveObject(m)` is called it will fail, but the `fail` handler https://github.com/BlueSpire/Durandal/blob/Next-Version/src/plugins/js/router.js#L430 will never be triggered, navigation will then be stuck and nothing will be logged about why the module failed to load.

One solution would be to do something like this (but prettier hopefully):

```
system.defer(function(dfd) {
  system.acquire(instruction.config.moduleId).then(function(m) {
      var instance = system.resolveObject(m);

      if(instruction.config.viewUrl) {
          instance.viewUrl = instruction.config.viewUrl;
      }

      ensureActivation(activeItem, instance, instruction);
      dfd.resolve();
  }).fail(dfd.reject);
}).fail(function(err) {
    cancelNavigation(null, instruction);
    system.error('Failed to load routed module (' + instruction.config.moduleId + '). Details: ' + err.message, err);
});
```

However this could be fine if durandal used something like `q` instead of jquery deferreds. I know you can override it, however I am reluctant to doing that since durandal never calls .done() https://github.com/kriskowal/q/wiki/API-Reference#promisedoneonfulfilled-onrejected-onprogress anywhere, and unhandled exceptions will then go unnoticed

**Comment by davismj** [comment]
Thanks for the feedback, I will review.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
