### ISSUE TITLE
Cross-origin security error when history.root =='/' with pushstate enabled.

### ISSUE THREAD

**Issue by jmwnoble** [BlueSpire/Durandal#561]
Updating from v2 to 2.1, the history plugin broke my app in history.navigate as it lost the protocol and host when navigating back to the root.  

At #L247 , var url = history.root + fragment had nothing for history.root, which was a problem at #L256.

As a quick workaround I added:

``` javascript
var fullRoot;
        //Make sure the root is the current protocol and host
        if (history.root == '/') {
            fullRoot = window.location.protocol + "//" + window.location.host;
        }
        else {
            fullRoot = history.root;
        }
//Then some code to make sure fragment has a starting slash

var url - fullRoot + fragment
```

I sense I've got something wrong in the implementation of my app to have to insert this, but thought I'd flag it all the same...

**Comment by davismj** [comment]
Thanks, I will review. If you have a repo that I could review that reproduces the issue that would be helpful.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
