### ISSUE TITLE
Using custom view strategy - Lifecycle fails when using same moduleid sequently

### ISSUE THREAD

**Issue by S-K-A** [BlueSpire/Durandal#581]
Hi! In our application we use a custom view strategy to retrieve html-fragments from an application server. We heavily rely on the correct lifecycle / invocation order of things.
When navigating the same route twice (which will likely receive different html-fragments via custom view strategy) we faced the problem that because of the same modules in charge for the view, the router fires "router:navigation:composition-complete" even before the strategy has been executed for this navigation.
The problem is:
https://github.com/BlueSpire/Durandal/blob/master/src/plugins/js/router.js#L323

firing attached and compoComplete...

I patched this line to a static false value and the problem is gone.

In fact I don't know if I can work around this behaviour, but even using

canReuseForRoute: function() {
            return false;
        }, 

in the modules failed to keep the lifecycle in good order.

Cheers!

**Comment by davismj** [comment]
Thanks for the nice bug report, I will review.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
