### ISSUE TITLE
Clarifications suggested for "Binding Plain Javascript Objects" docs page

### ISSUE THREAD

**Issue by navels** [BlueSpire/Durandal#584]
Couple of suggestions for this page:
1. The bit about computed properties (with getter and/or setter) being automagically converted to knockout computed observables.

This is a great feature of 2.1.0 and deserves to be called out with an example.
1. That properties that start with '_' or '$' are not converted into observables.

This particular one had me scratching my head quite a bit, although it is in the API documentation for observable.convertObject.

**Comment by davismj** [comment]
Thanks for the feedback. I'll take a look and see what we can do to clear that up!

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
