### ISSUE TITLE
Loading a view through app.setRoot() does not set the isProcessing flag

### ISSUE THREAD

**Issue by navels** [BlueSpire/Durandal#585]
Durandal has code that protects against two lifecycles occurring simultaneously, using an "isProcessing" flag in router.js.  The flag is set whenever a navigation event occurs and reset at the end of the composition lifecycle.

The problem is that app.setRoot() loads a view without going through the navigation code and so this flag does not get set, but it does get cleared when the shell is finished composing, leaving open the possibility of this:

1. shell begins activation
2. user navigates to view A.  this is allowed because isProcessing is false.
3. that navigation causes isProcessing to be set true.
4. shell completes composition.  this clears the isProcessing flag.
5. user navigates to view B.

at this point Durandal is processing both views A and B.

Workaround for us was for our app to not expose the navigation controls until after the shell had completed composition (it had been after activation).  That seems more correct anyway but still a bug in the framework.

**Comment by davismj** [comment]
Actually, I've personally run into this issue. Sadly, I think it will not be fixed. The router has a few issues that have been resolved in Aurelia and otherwise have reasonable workarounds in Durandal. @EisenbergEffect recommend close.

**Comment by davismj** [comment]
Actually, this issue is exactly what we're seeing in https://github.com/aurelia/framework/issues/212. Seems that most of the code is conceptually identical.

**Comment by navels** [comment]
interesting :)
