### ISSUE TITLE
Update to Knockout 3.2

### ISSUE THREAD

**Issue by EisenbergEffect** [BlueSpire/Durandal#586]

**Comment by TOuhrouche** [comment]
I am using Durandal 2.1.0 and just updated to Knockout 3.2. My SPA is now getting stuck with no error messages. I didn't manage to sport the error yet... everything was working fine with ko 3.0.0

**Comment by gogocat** [comment]
Does Durandal works with lastest Knockout? with Knockout component?

**Comment by TOuhrouche** [comment]
Yes it does :)

**Comment by AdamWillden** [comment]
Also confirming it does

**Comment by gogocat** [comment]
AWESOME!
