### ISSUE TITLE
Router moduleId as function

### ISSUE THREAD

**Issue by zewa666** [BlueSpire/Durandal#588]
Hi there,

I have no idea if that has been discussed elsewhere maybe, but an issue search didn't brought that up. It would be very helpful if we could assign a function instead of strings to the moduleId, where we map routes to the router.

The idea is that this way you could overcome some special scenarios, where depending on route instructions you'd have to decide which module to activate.

Take the router example from the documentation:

````
...
{ route: 'tickets',             moduleId: 'tickets/index',                          nav: true   },
{ route: 'tickets/:id',         moduleId: 'tickets/thread'                                      },
...
````

with a function for the moduleId we could do something like:

````
...
{ 
   route: 'tickets(/:id)',
   moduleId: function(instruction, router) {
      if(// check instructions for presence of optional id) {
        return 'tickets/thread';
      } else {
        return 'tickets/index';
      }
   },
   nav: true 
},
...
````

Now that's maybe not the best example, but I hope at least its understandable what I'm asking for :)

**Comment by davismj** [comment]
@EisenbergEffect recommend close, sorry vildan :( it's a great idea though!

**Comment by EisenbergEffect** [comment]
We did get this into Aurelia at least ;)
