### ISSUE TITLE
__moduleId__  is undefined in firefox

### ISSUE THREAD

**Issue by dziamid** [BlueSpire/Durandal#589]
I am experiencing this very strange issue: on occasion some modules are not passed through `system.setModuleId` function and threfore view location failes to load their respective views based on `__moduleId__` property. This issue is only relavant to Firefox. In Chrome there's no such issue.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
