### ISSUE TITLE
navigatingBack bug when clicking anchor

### ISSUE THREAD

**Issue by martinbooth** [BlueSpire/Durandal#594]
Durandal assumes that when you click an anchor, you are navigating to a new location. It sets explicitNavigation to true in:

            $(document).delegate("a", 'click', function (evt) { ... }

The problem is, anchors are commonly used simply to trigger something to happen such as the bootstrap dropdown:

            <a data-toggle="dropdown" href="#">
                <i class="fa fa-angle-down"></i>
            </a>

This triggers the durandal event handler and means that next time the user clicks the back button, navigatingBack is false when in fact it should be true. Not sure what the possible fix would be for this one

**Comment by davismj** [comment]
will review @EisenbergEffect please assign to me

**Comment by EisenbergEffect** [comment]
Assigned to you :)

**Comment by martinbooth** [comment]
The issue is caused by durandal assuming:

* Clicking a link followed by a change to the url means the user navigated forwards
* A change to the url (without a click on a url preceeding it) means the user must have clicked back

If you click a link which has a click handler preventing navigation occurring then durandal assumes that the next change to the url was explicit (rather than the back button having been clicked), yet it is entirely possible that the navigation was not explicit (i.e. the back button had been clicked) because durandal set this explicitNavigation flag even though the browser never followed the link when it was clicked.

The two new lines above (in my previous comment) ensure this flag is not set if the default action has been prevented and fix this issue. It applies to router.js approx line 1057

It may also be necessary to check that the link target is different than the current url (probably a bit of work considering targets may be relative, etc) because I don't think durandal will detect a history event if the hash/url doesn't actually change.. This would lead to the same problem
