### ISSUE TITLE
Feature Request:  Synchronous composition

### ISSUE THREAD

**Issue by srowan** [BlueSpire/Durandal#598]
I am the tech lead for a fairly large application (10 developers) which uses durandal.   In general, we are extremely happy with the framework.   Our biggest headache however is the jerky/janky rendering experience which stems from the asynchronous nature of the compose and widget bindings.   The issue is mostly imperceptible in demo / hello world applications, but in large mature applications it becomes overwhelming.

This was also an issue with the recently-released components feature of knockout, for which I added a feature request here: https://github.com/knockout/knockout/pull/1504  (a fix has been added to their development branch, but not yet released).   Please read that issue for good background information on the problem.

This is helpful, but obviously not ideal since knockout widgets do not participate in the composition/activation lifecycle or some of the other goodness that the compose binding gives us.

I believe that in order to receive good rendering efficiency, widgets and the compose binding must render synchronously when possible (such as when the application has been bundled).  The ability to render the page top-to-bottom will not only get rid of the janky loading experience, but should greatly improve the performance hit of layout thrashing.

Note: Obviously, viewmodels which return a promise from activate must be loaded asyncronously - this issue mainly concerns UIs built up from a deep graph of viewmodel components.

**Comment by dancras** [comment]
We also struggle with this. Our very slight workaround for the rendering is to make our widgets etc render lists, rather than individual items so that there are fewer compose calls.

Today I have an issue with iOS devices and setting form field focus programatically which must be done on the same stack frame as a user interaction event. Unfortunately due to the async nature of compose, the element isn't rendered during that stack frame.

**Comment by dancras** [comment]
Here's a branch experimenting with synchronous composition. Seems to work ok on my project so far.

If someone could explain what all the setTimeouts were solving I'd be very grateful.

https://github.com/dancras/Durandal/tree/synchronous-composition

**Comment by davismj** [comment]
@srowan have you reviewed @dancras ' repo above?

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
