### ISSUE TITLE
Optimization when binding view models

### ISSUE THREAD

**Issue by ioancrisan** [BlueSpire/Durandal#601]
There are cases when the same view should be used for different view models, like when a grid and detail view must be synchronized according to the current grid selection. In this case, the view model bound to the detail view changes, but there is no need to create a new view because the same view can be reused.

Possible resolution: add a method in the composition module for override, which should indicate whether the view can be reused or not.

**Comment by davismj** [comment]
@ioancrisan can you submit a pull request for this item?

**Comment by ioancrisan** [comment]
I think there is already a pull request, or did I do something wrong that you don't see it?
Issue #599 - Support for TypeScript 1.3 #600 That should be the pull request containing this optimization

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
