### ISSUE TITLE
Provide module parameters in routes

### ISSUE THREAD

**Issue by ioancrisan** [BlueSpire/Durandal#603]
I am using in a project routers with child routers and parameterized routes. One thing that I am missing is that, when instantiating modules over route configurations, I don't have too much options instead of the moduleId value which provides the file name of the module to be instantiated. I would like here to be able to provide a parent router parameter, so that the instantiated view model can create its child router based on this parent router. Currently, I have to define multiple derived view models of the same class for each route path where a view model is used, only to be able to identify the parent router.

It is acceptable to assume that the route's module parameters will be used only when the Durandal module loaded with the moduleId is a factory function.

P.S. I just saw the post that Durandal vNext is alive and kicking (http://eisenbergeffect.bluespire.com/leaving-angular/), so I thought I can bring my own experience in advancing Durandal.

**Comment by davismj** [comment]
can you include some code related to this issue, and an example of how you would like/expect this to behave?

**Comment by ioancrisan** [comment]
Well, when defining the routes I could provide an object/factory function to get an object. This object is then passed to an initialize() method of the module, together with some durandal context. This should be similar to activate, only it is called only once, upon initialization.

**Comment by davismj** [comment]
Unfortunately, I don't think this will make it into Durandal. However, please take a look at Aurelia's may release blog. I think the `generateRoute` function will achieve something similar to what you're looking for here. If not, we'd love to hear a bit more feedback as well as get some code examples of what you're looking for.

@EisenbergEffect I'd close this as it is a feature request that seems to be solved with Aurelia.
