### ISSUE TITLE
HTML starter kit & Bootstrap reactive menu

### ISSUE THREAD

**Issue by MarkStega** [BlueSpire/Durandal#604]
Acquiring & running the 2.1 HTML starter kit (i.e., opening index.html in Firefox) I notice the following behavior: When the browser window is made narrower than 768 pixels the menu appropriately collapses to the icon form. However, clicking on the menu icon causes it to change its rendering but not to show the collapsed menu. It is as if the Bootstrap js code is not running. I am not familiar enough yet with this environment to debug.

**Comment by derkan** [comment]
Please add bootstrap on `main.js` to let bootstrap javascript to be loaded:

```js
define(['durandal/system', 'durandal/app', 'durandal/viewLocator', 'knockout', 'bootstrap'],
function (system, app, viewLocator, ko) {
...
```

**Comment by davismj** [comment]
@EisenbergEffect this is in fact not a bug and the solution proposed by @derkan is correct, this item can be closed
