### ISSUE TITLE
Strange routing behaviour when using pushState on webforms

### ISSUE THREAD

**Issue by ganySA** [BlueSpire/Durandal#607]
I am using a .net forms aspx project to host durandal. When my project is configured without the pushstate: true property set it works correctly... however when i  enable the pushState routes without parameters work correctly however those with parameters break.

An example using the router line below:
{ route: 'search/:query1/:query2', moduleId: 'viewmodels/search', nav: true }

The router seems to cut something short in parsing the above and attach the path to the viewmodel.... it seems to simply append the module that it should load....

https://xxx/search/2ffe696b-fcb0-486b-a7a2-086fd2209f5a/app/viewmodels/search.js Failed

**Comment by davismj** [comment]
will review, @EisenbergEffect please assign to me

**Comment by EisenbergEffect** [comment]
@davismj I can't "officially" assign it through GitHub without jumping through some hoops. But, consider this an "assignment" ;) Please go ahead and take it on. Thanks!

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
