### ISSUE TITLE
Broken "Testing with Grunt" link in docs

### ISSUE THREAD

**Issue by BBosman** [BlueSpire/Durandal#608]
On the [Docs](http://durandaljs.com/docs.html) page there is a link called `Testing with Grunt` under the `Testing` section, which points to a non-existing page. 

I assume it' supposed to point to the [Building and Testing with Grunt](http://durandaljs.com/documentation/Grunt.html) page.

**Comment by EisenbergEffect** [comment]
Going out today in the next site release.
