### ISSUE TITLE
Empty View throws error

### ISSUE THREAD

**Issue by paranoxx** [BlueSpire/Durandal#614]
Using an empty view throws an error in viewEngine.js in method "ensureSingleElement" since allElements only contains empty string instead of DOM node.
Same in "createView" after processMarkup is called.

**Comment by niix** [comment]
@paranoxx I've run into this a couple of times, the only solution I can find is by creating DOM element i.e. `div` or `section`, etc..  Looking at the source it looks like this may be intentional?  Maybe @EisenbergEffect can weigh in, if not I can make a PR for the fix.

**Comment by PWKad** [comment]
What is the use case?  Why would we need to require in an html file with no mark-up?  Trying to understand the issue better.

**Comment by niix** [comment]
@PWKad I guess its more that everything needs to be wrapped in some element, iirc

**Comment by davismj** [comment]
The use case is when you are creating a child routing scenario with an empty child route. Let's say you have a master-detail view and you want to save-and-close the detail, you might want to depopulate the view.

I can look into guarding this by creating an empty element if no markup is provided.
