### ISSUE TITLE
Broken URL in Understanding the Samples

### ISSUE THREAD

**Issue by Svish** [BlueSpire/Durandal#618]
In the documentation under [Understanding the Samples](http://durandaljs.com/documentation/Understanding-the-Samples.html) there's a link to [See the samples in action now!](http://durandaljs.com/pages/samples) which just gives me a GitHub Pages 404 :(

**Comment by EisenbergEffect** [comment]
Going out in the site update today.

**Comment by unsystemizer** [comment]
@EisenbergEffect, it's (still | again) broken
