### ISSUE TITLE
Problem faced in 2nd level routing, on declaring 3 level child router

### ISSUE THREAD

**Issue by Ashwini6** [BlueSpire/Durandal#621]
Hi,

Third level routing issue(https://github.com/BlueSpire/Durandal/issues/357) is solved, but I am facing problem in 2nd level routing.

Once I declare 3rd level router, I am facing problem in navigation between modules defined in 2nd level router.
The issue is: when I navigate in between different modules at 2nd level router, activate is fired but attached is not fired for the module.

Code snippet for routers is as follow:

//1st level router
landing.router = router.map([
                { route: 'resourcebrowser*splat', title: 'Resource', moduleId: 'viewmodels/resourcebrowser', nav: true },
]).buildNavigationModel();

//2nd level router
var childRouter = parentView.router = landing.router.createChildRouter()
    .makeRelative({
        moduleId: 'viewmodels/tab/',
        fromParent: true
    }).map([
        { route: ':id/details', moduleId: 'details', title: 'Details', type: 'intro', nav: true },
        { route: ':id/docs*splat', moduleId: 'documents', title: 'Documents', type: 'intro', nav: true }
    ]).buildNavigationModel();

//3rd level router  
   var childRouter = parentView.router.createChildRouter()
           .makeRelative({
               moduleId: 'viewmodels/viewer/',
               route: ':id/docs/'
           })
       .map([
           { route: 'documentviewer/:docid', moduleId: 'documentviewer', title: 'Viewer', type: 'intro', nav: true }
       ]).buildNavigationModel();

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
