### ISSUE TITLE
Starterkit route issue

### ISSUE THREAD

**Issue by mryellow** [BlueSpire/Durandal#622]
When doing a durandal grunt task build of a project based on the starterkit I have come up against a route error. 

Initially hitting the app with my defined routes `#settings` or `#search` works fine, however if the project is hit without a route an error results: 

```
TypeError: instance is undefined
http://localhost:9001/app/main.js
Line 3820
```
Which is:
```
function hasChildRouter(instance, parentRouter) {
    return instance.router && instance.router.parent == parentRouter;
}
```

So routes are working, it's not a relative path issue, but the `welcome` route fails.

https://github.com/BlueSpire/Durandal/blob/master/src/starterkit/app/viewmodels/welcome.js

It appears to be this needs the app module loaded:

```
define(['durandal/app'], function (app) {
```

**Comment by PWKad** [comment]
@mryellow Could you submit a PR with the above code changes and corresponding tests?  Should be simple enough to emulate the workflow you described and showing it doesn't break any more, if not just let me know.

**Comment by mryellow** [comment]
Will be good practice for me, haven't done a public PR before, should be straight-forward enough. 

Was day-dreaming about this one the other day and it may be a little quirky. My builds had been working, something changed, I imagine `app` was on a global scope somewhere or some sync issue with things being loaded in time.

Will see what I can do over the next few days.

**Comment by davismj** [comment]
How is this coming along?

**Comment by mryellow** [comment]
Been a bit busy.... but thinking about it I'm not sure there is anything to test, or that I can easily duplicate the issue. Was something that only popped up when boiling down the config to a more production ready build and was changing a few things at once when it happened.
