### ISSUE TITLE
observable.convertObject should return the object

### ISSUE THREAD

**Issue by navels** [BlueSpire/Durandal#624]
So I can write

    return observable.convertObject( new MyModule() );

instead of

    var myModule = new MyModule();
    observable.convertObject( myModule );
    return myModule;

I can submit a pull request...

**Comment by PWKad** [comment]
@navels Please submit a PR if you have some working code here.  Also be sure to include test cases to cover the change in functionality.

**Comment by navels** [comment]
There are currently no tests for the observable plugin (unless I am looking in the wrong place...).  I suppose I could add one.

**Comment by PWKad** [comment]
Would be great, I don't see any around the observable plugin yet so it would be a good start.

**Comment by davismj** [comment]
@navels any luck with this pr? i see you have another outstanding pr for a different issue?

**Comment by navels** [comment]
Just haven't gotten around to it.  Maybe the juice isn't worth the squeeze :)
