### ISSUE TITLE
Router module removes empty URL parameters from activation parameters

### ISSUE THREAD

**Issue by ashrafsabrym** [BlueSpire/Durandal#625]
I have the following navigation operation:
```javascript
router.navigate("account-receivable/sales-details?" + $.param({
            branchId: branchId
        }));
```
When `branchId` is `null` the resulting query string is `branchId=`.
In the router module, `router.parseQueryString` causes this null value to be removed altogether from the parameters passed to the module I navigate to, which is not desirable, as I want the parameter to be passed as null, as this has special meaning to the other module.
I had to modify line 557 in router.js as follows:
`value = (parts[1] && decodeURIComponent(parts[1].replace(/\+/g, ' '))) || null;`
I added the `|| null` part. Before this fix, `value` gets the value of `undefined` which makes the key not to be added to the query object.

**Comment by TOuhrouche** [comment]
From an API point of view, you should never use `null` as a signaling parameter to other modules. `null` has a special meaning and semantics in the language and should not be used for such use cases. 
Wouldn't it be simpler to pass in a special defined value (a magic string for example)?

**Comment by ashrafsabrym** [comment]
The expression in router.parseQueryString tests for truthy values, so, even using an empty string won't work (the regex sets parts[1] to `undefined`).
Null makes sense for this view model. It means "search for all branches". I don't like sending special values like 0 or -1. I want to send an empty URL parameter the same way we do with web handlers URLs.

**Comment by PWKad** [comment]
@ashrafsabrym - can you submit the modification as a Pull Request for review on this issue?

**Comment by ashrafsabrym** [comment]
My fix was just adding `|| null` after the mentioned line, and it worked well, and the controller/viewModel gets the null value.
I'll issue the pull request tomorrow when I'm on my office because the code is not available to me now.

**Comment by ashrafsabrym** [comment]
I issued the request

**Comment by PWKad** [comment]
@EisenbergEffect I didn't get a chance to review this PR until now but I believe this was not a PR from the latest verison of router.js including this change - 

https://github.com/BlueSpire/Durandal/commit/fe4ce68986e427ca7e0462e83c5e4b6f845ceb6b#diff-0d9e763c6e75932eaad003c8584b0105

It appears to be related to #628

**Comment by EisenbergEffect** [comment]
Yes, I believe this is now fixed.
