### ISSUE TITLE
Router code inconsistency after last commit

### ISSUE THREAD

**Issue by StrahilKazlachev** [BlueSpire/Durandal#628]
There is something wrong in the router after the [last commit](https://github.com/BlueSpire/Durandal/commit/2a4a393ef38bac517585f3da74622959530d963b).
[value = (parts[1] && decodeURIComponent(parts[1].replace(/\+/g, ' '))) || null;](https://github.com/BlueSpire/Durandal/blob/2a4a393ef38bac517585f3da74622959530d963b/src/plugins/js/router.js#L553)
[value = sp === -1 ? null : decodeURIComponent(pair.substr(sp + 1).replace(/\+/g, ' '));](https://github.com/BlueSpire/Durandal/blob/2a4a393ef38bac517585f3da74622959530d963b/platforms/Bower/Durandal/js/plugins/router.js#L558)

**Comment by PWKad** [comment]
Could you explain what the issue you are having is please and / or steps to reproduce?
