### ISSUE TITLE
Special characters in route parameters and child router

### ISSUE THREAD

**Issue by StrahilKazlachev** [BlueSpire/Durandal#637]
An application I work on has as route parameters IDs that do not have symbols restriction, hence can contain '/' or '//', etc. When such parameter is part of a child router the matching breaks because the fragment is [reconstructed by joining the parameters as is](https://github.com/BlueSpire/Durandal/blob/2.1.0/src/plugins/js/router.js#L600). But they are already [url decoded](https://github.com/BlueSpire/Durandal/blob/2.1.0/src/plugins/js/router.js#L449) and when the parameter contains '/' or '//' the matching fails. As a work around I provide in the route config my own `RegEx`. But it turned out this was not enough in the case when there are sequences of '//' in the parameter because of [this line of code](https://github.com/BlueSpire/Durandal/blob/2.1.0/src/plugins/js/router.js#L449). ~~Re-encoding the the parameters when reconstructing the fragment should fix this.~~
 Also would it be appropriate to add a method to the router similar to `makeRoutesCaseSensitive` that instructs the router not to decode the parameters in the first place - `turnOffParameterDecoding` or something?

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
