### ISSUE TITLE
Parent Child-View-Swaping Problem

### ISSUE THREAD

**Issue by CognitiveFeedback** [BlueSpire/Durandal#638]
demo: http://durandal-demo.neocortex.com.au/
download project: http://neocortex.com.au/media/codeprojects/durandal.demo.zip

Hi ... 

I am having trouble with activation life-cycle in a parent-router. 

The problem is specifically the re-activation of a parent viewmodel. 

The problem is when the user navigates back to the parent viewmodel, durandal does the following: 
1. Renders ('composes') the previously active child-viewmodel, then
2. Discards ('deactivates') that child-viewmodel, then
3. Composes and activates the correct child-viewmodel targeted by the current route.

The result is that the user experiences a 'page-flash' (or 'page-swap') as the parent's view is incorrectly-composed-and-then-switched-out from the previous-view to the correct view specified by the given route.

The problem occurs at step 1.

I am hoping to get some help to prevent this so that the parent's default child-viewmodel loads without the problematic 'page-switching'/'page-flash' problem.

Reproduce the problem: 
1. Click on the Projects menu item (top-right of the app)
2. Click on one of the page items to activate one of the child-routes
3. Click on the Dashboard menu item
4. Click on the Projects menu item again (and notice the page-flash problem prior to the default-page load)

NOTE: The solution needs to specifically fix the parent router's view switching issue described here so that URL routes to child-views are maintained. For example: not explicitly manipulatiung durandal/activators so that the URL no longer represents child views, (i mention this because someone raised this same issue previously and switching child-views using durandal's activator object was the solution proposed ... but that is not going to be an appropriate solution in this case).

**Comment by davismj** [comment]
So basically, when there are two view models with child routers, when navigating from one parent to the next, the child from the first is initially composed as the child of the second?

**Comment by CognitiveFeedback** [comment]
almost ... 
when there are two view models, one of which has child routes, when navigating from this parent-viewmodel to the next and then returning to this parent-viewmodel, Durandal re-composes the previously active child-viewmodel before suddenly deactivating it and composing the child-viewmodel specified by the actual route URL.

**Comment by KevinTuttle** [comment]
I also ecounter this issue with our Durandal app.

**Comment by CognitiveFeedback** [comment]
thanks davism for asking about this issue and thanks Kevin for confirming this

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
