### ISSUE TITLE
Durandaljs.com site issues in mobile / responsive

### ISSUE THREAD

**Issue by genereddick** [BlueSpire/Durandal#640]
I'm seeing issues with the site on menu collapse on mobile (Android) and in a small browser size (Chrome & IE 11).

In browser the nav menu items (Get Started, Downloads, Docs) correctly disappear and the hamburger dropdown shows up, but clicking it doesn't expand the dropdown.

On mobile, the large font Durandal title is partially overlaid by the nav and the page does not fit the browser window. The hamburger is scrolled off to the right outside of the window. It also does not expand on click.

**Comment by davismj** [comment]
Thanks for the report. I've been able to reproduce and I should be able to fix it. @EisenbergEffect how do I go about resolving issues with the site itself?

**Comment by EisenbergEffect** [comment]
Hmmm. The actual site source is in a private repo. Let me see what it would take to give you access there.

**Comment by EisenbergEffect** [comment]
@davismj I've given you access to the site source. You will see the readme file there which should explain how to get up and running. Please fork and send me a PR to review. Make sure to only commit stuff in the src folder please. Thanks!

**Comment by davismj** [comment]
@EisenbergEffect this should fix the issue, and this issue can be closed
