### ISSUE TITLE
Observable plugin early convertProperty fired without hasChanged

### ISSUE THREAD

**Issue by mryellow** [BlueSpire/Durandal#642]
```
function ModelFoo(input) {
    this.hasChanged = function (obj, propertyName, newValue, arrayChanges) {
        console.log('hasChanged', obj, propertyName, newValue, arrayChanges);
    };

    this.bar = '';

    console.log(observable(this, 'bar')); // `convertProperty` triggered
}
return ModelFoo;
```

When touching `observable(this, 'bar')` the property is converted, however `convertProperty` is called with `hasChanged == undefined`.

Later when bindings are applied, the remaining fields are converted with `hasChanged` correctly set.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
