### ISSUE TITLE
Dynamic route parameter

### ISSUE THREAD

**Issue by gcastre** [BlueSpire/Durandal#645]
The named parameter are not resolve with convertRouteToHash in a childRouter view.

I have made a branch with a modification of the sample you can see the diff here: https://github.com/BlueSpire/Durandal/compare/master...gcastre:dynamicRouteIssue?expand=1

The url of the <a> will be #keyed-master-details/:id/second instead of #keyed-master-details/1/second

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
