### ISSUE TITLE
html5 elements in IE8

### ISSUE THREAD

**Issue by sebihanu** [BlueSpire/Durandal#647]
Hi, I need to make a durandal project that contains html5 elements (like article) to work with IE8.
So, I have the following section in a view: "< article>Welcome< /article>"
in a custom css I have: article { display: block; border: 1px solid red }
and of course the modernizr.js library added to the head section of the page.
The result is that in IE8 the article element isn't bordered.

If I try to load the view manually with something like 
    require(['text!hello/index.html'], function (html) {
                $("#test1").append(html);
            });
everything looks fine.

Thanks

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
