### ISSUE TITLE
Widget recomposing/reactivating inconsistently

### ISSUE THREAD

**Issue by navels** [BlueSpire/Durandal#648]
I am seeing some inconsistent behavior with widget composition.  Here's an example:

http://navels.github.io/dFiddle-2.0/#widgets/composition

This is a simple widget that is passed a settings object when composed into the parent.  The parent has a couple of buttons for modifying the settings object and those modifications are reflected in the widget's view.  So far so good.

What I don't understand is, if I modify a top-level property of the settings object (in this case: settings.text), it causes the widget to be recomposed (so the widget activate/bind/etc lifecycle is triggered), but if I modify a "sub-property" (in this case: settings.obj.text) it does not.

Is this the intended behavior?  If not, which is correct?

ps I'm using the observable plugin

**Comment by navels** [comment]
Hmmmm...I just tried using data-bind="compose.." instead of the widget syntax and that did not exhibit repeated activation.

**Comment by davismj** [comment]
@navels thanks for the feedback, from my personal experience, the observable plugin is a little picky about when and how you instantiate stuff.

```javascript
var settings = {
    text : 'FOO',
    obj : { text : 'BAR' }
};

return {
  settings : settings,
```

So, I believe when you return settings: settings, the observable plugin looks at settings and converts all the properties to an observable behind the scenes. In this case, I think it would look at your settings object and make an observable out of text and obj, which describes the behavior you're seeing.

Try this:

```
define(['plugins/observable'], function () {

  var vm = {
    settings = {
      text : 'FOO',
      obj : { text : 'BAR' }
    },

    changeText : function() {
      settings.text = settings.text === 'FOO' ? 'foo' : 'FOO';
    },

    changeObjText : function() {
      settings.obj.text = settings.obj.text === 'BAR' ? 'bar' : 'BAR';
    }
  };

  observable(vm, 'settings');
  observable(vm.settings, 'obj');

  return vm;
});
```

Let me know if this works. I'm not sure if this is something we ought to fix. What are your thoughts?

**Comment by navels** [comment]
I don't think I made myself very clear, but I think I've gotten to the bottom of it.  When using the widget or compose syntax:

    <div data-bind="widget: {...}"></div>
    <div data-bind="compose: {...}"></div>

the appropriate bindingHandler (for widget or compose) goes through each top-level property in the `{...}` and adds it to the dependences of the handler's update method.  This means that if any of those properties changes, the update will run again, running the activate/compose/etc lifecycle again.

The difference between widget and compose:

    <div data-bind="widget: { kind: 'myWidget', items: projects }"></div>
    <div data-bind="compose: { model: 'path/to/viewmodel', activationData: { items: projects } }"></div>

Because the widget activation data (items) is mixed with the other widget config properties (kind) at the top-level, it will be added to the dependencies of the widget bindingHandler update method.  Whereas the activation data for compose is wrapped inside the activationData property, so the activationData object will be a dependency of update but activationData.items will not.

I would have preferred a common syntax and behavior, like this:

    <div data-bind="widget: { kind: 'myWidget', activationData: { items: projects } }"></div>
 
which would involve deleting a line of code from widget.createCompositionSettings (see comment):
    
        createCompositionSettings: function(element, settings) {
            if (!settings.model) {
                settings.model = this.mapKindToModuleId(settings.kind);
            }

            if (!settings.view) {
                settings.view = this.mapKindToViewId(settings.kind);
            }

            settings.preserveContext = true;
            settings.activate = true;
            // comment out the following line
            // settings.activationData = settings;
            settings.mode = 'templated';

            return settings;
        },

and would also mean that the settings object in the widget's activate method would just have the user-specified activation data instead of all the other bits of this "settings" object.  (See this stackoverflow post where someone was asking about this and did not really get an answer: http://stackoverflow.com/questions/27171049/durandal-activationdata-nested-in-widget)

In addition to deleting this one line, you'd also want to add "activationData" to the bindableSettings object in widget.js.

As is, this would be a breaking change for folks using widgets, although you could protect against it.  Instead of deleting that line, do this:

    if ( !settings.hasOwnProperty('activationData') ) {
        settings.activationData = settings;
    }

That seems pretty safe to me, and now the syntax for activationData is consistent and the widget doesn't reactivate/recompose every time some piece of activationData changes.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
