### ISSUE TITLE
Attached fires twice on child viewmodels when they have been activated more than once

### ISSUE THREAD

**Issue by esbenp** [BlueSpire/Durandal#650]
I have two viewmodels 1 and 2. Each is a parent router and each has one child route subview 1 and 2. If i activate subview one and then switch to subview 2 attached is firing once for each subview as expected. However, if I then go back to subview 1 attached is firing twice. Similar behaviour occurs for subview 2. I have made a demo repo here https://github.com/esbenp/durandal-bug

Basically just open the console and click between the two links in the navigation bar.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
