### ISSUE TITLE
Durandal 1.2.0 typescript sample

### ISSUE THREAD

**Issue by gyancse08** [BlueSpire/Durandal#651]
Hi All,
       Does any one tried creating views and viewmodels in typescript for durandal 1.2.0. 
Our project has grown a lot and it's a huge cost for us to migrate to durandal next versions (It has breaking changes). Also Durandal 1.2.0 has worked quite well for us so we are not greedy to move to next version. The only good part we wanted in this project was to integrate typescript. Please let me know if it is available or any pointers using which I can create a sample Typescript template for durandal 1.2.0.

**Comment by davismj** [comment]
@gyancse08 It's so good to hear that you've been successful with Durandal 1.2.0. Unfortunately, I wasn't able to find anyone who has tried using typescript with Durandal 1. I would recommend that you try posting on stackoverflow with the durandal and typescript tags, or asking around the aurelia gitter at https://gitter.im/Aurelia/Discuss. 

@EisenbergEffect this issue can be closed

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
