### ISSUE TITLE
Default parameters for "activate"

### ISSUE THREAD

**Issue by mjac** [BlueSpire/Durandal#656]
I wanted to make a primary navigation which used the same module twice. However I couldn't find a way to pass a default parameter to the module to indicate which version of the page I wanted.

My solution was to add a default parameter array to the router configuration similar to MVC:

    { route: 'exercise/bench', params: ['bench'], moduleId: 'modules/exercise/index', title: 'Bench press', nav: true }
    { route: 'exercise/squat', params: ['squat'], moduleId: 'modules/exercise/index', title: 'Squat', nav: true }

Would it be possible to review my pull request to see if it is appropriate for inclusion in the mainline branch?

Please let me know if there is a better way to go about this.

**Comment by leftclickben** [comment]
@mjac you can access the current route parameters using `router.activeInstruction().config`.  This is available at least in the `activate()` method.  So in `activate()`, if you defined your routes as per your OP, then you could use something like, `var params = router.activeInstruction().config.params;` and then `params[0]` would be either "bench" or "squat" depending which route you are on.  HTH.

**Comment by mjac** [comment]
Sounds good, thanks for the advice. Should we close this one then?
