### ISSUE TITLE
Named Modules

### ISSUE THREAD

**Issue by marvc1** [BlueSpire/Durandal#661]
Is it possible to have named modules?

I.e instead of 

``` javascript
    define(['require', 'jquery'], function(require, $) { //...
```

We would have

``` javascript
    define('durandal/system', ['require', 'jquery'], function(require, $) {
```

This way Durandal can easily be packaged with existing bundling methods (ASP.NET bundling) without having to add a JavaScript build method, which is overkill for most existing ASP.NET projects.

**Comment by ibrahimbensalah** [comment]
isn't it a requirejs related question? here is an example taken from requirejs doc page http://requirejs.org/docs/api.html#deffunc 

    //Explicitly defines the "foo/title" module:
    define("foo/title",
        ["my/cart", "my/inventory"],
        function(cart, inventory) {
            //Define foo/title object in here.
       }
    );

**Comment by marvc1** [comment]
@ibrahimbensalah it is about the RequireJs modules yes, however it is the implementation of the modules within Durandal  that this issue talks about. 

If you want to bundle anonymous RequireJs modules you need a custom build method to give the modules names based on their location within the project. I don't know of a reason why the modules inside of Durandal cannot have explicit names. There may be a reason.

If there is no reason why Durandal cannot have explicitly named modules, then I think it would be better to have names, that way we can bundle the Durandal files without having to apply a custom build method which adds the explicit names.

**Comment by ibrahimbensalah** [comment]
@marvc1 I totally agree, but just to be clear, can you confirm that named modules are not working, inside durandaljs? as far as I know, durandaljs relies on requirejs without any additions.

**Comment by marvc1** [comment]
Named modules work perfectly inside Durandal. 

If there is no reason why the main repo cannot have explicitly named modules, it would be nice if we could name them, as currently I am manually changing them each time there is an update. I expect quite a lot of  people are using Durandal in this way.

The bundles are just a script tag.

**Comment by weiran** [comment]
Just use Gulp.

**Comment by shameen** [comment]
There doesn't look to be any reason why not to do this. I too use Asp.Net MVC bundling and named modules would save a whole lot of effort.

**Comment by leftclickben** [comment]
The reason I can see not to do this is that it's explicitly recommended against in the requirejs documentation.  

http://requirejs.org/docs/api.html#modulename

> These are normally generated by the optimization tool. You can explicitly name modules yourself,
> but it makes the modules less portable -- if you move the file to another directory you will need to
> change the name. It is normally best to avoid coding in a name for the module and just let the
> optimization tool burn in the module names. The optimization tool needs to add the names so that
> more than one module can be bundled in a file, to allow for faster loading in the browser.

That issue of portability means that if someone moves a file and forgets to change the name to match, or makes a typo in the name, then the module will not be loadable.  Essentially you are taking the single source of truth for module names, being the file structure, away and replacing it with a less reliable and less obvious source of truth.

As for using ASP.NET MVC bundling, I'm struggling to see why you would do this.  ASP.NET is a server-side language and Durandal is a client-side framework.  There is an argument for keeping the tooling consistent across projects, but I think a better argument is "use the best tool for the job".  In the case of packaging a Durandal application, that best tool is the `r.js` optimizer, not a server-side bundling pipeline.  That's just my opinion though, possibly what I'm saying doesn't make sense in some circumstance I haven't considered.

**Comment by marvc1** [comment]
The use case for moving the files will be a very rare one, if at all. If you move the file manually, then you will be taking it outside of whatever package loader you have anyway. Which would break a Single Source of Truth principle. Another Faux Pas on the SSoTruth is that we have to configure Require Js to know where the Durandal folder is.

Adding your own funky folder structure for Durandal would also break the existing references in the Durandal files, which would then have to manually change the Durandal modules to know what the new names of the files were.

For Durandal, I would of thought a lot of the take up of it has come from .NET developers, and making it easy for them to use Durandal with existing projects would be beneficial to all of us.

On using the 'best tool for the job', the argument is based on circumstance and opinon. Adding additional tools to build mix, is perhaps what many don't want or need. It feels like swallowing a Cat to catch a Bird, when the real solution was to not swallow the fly in the first place. ;-P

I guess you have to weigh up the pro's and cons, but I haven't yet seen a con, apart from the recommendation in the RequireJs docs.

The pro's of it working with existing bundling methods, without having to add a client side build method (which is no small effort for someone who has not done it before, or working with anything legacy), and making it easier for a potentially large audience, out weigh the con IMO.

**Comment by AdamWillden** [comment]
> It feels like swallowing a Cat to catch a Bird, when the real solution was to not swallow the fly in the first place. ;-P

You've made my morning

**Comment by leftclickben** [comment]
@marvc1 To be clear, I meant that the explicit module id would be one more thing for the maintainers of Durandal to remember to update, if they ever move or add a file in some future version.  They currently do not need to update this because the module id is derived automatically from the file path by r.js.  I wasn't suggesting someone using Durandal would move any files themselves.

Personally it won't affect me if this recommendation is adopted, as long as the explicit module ids match the current, generated ones.  I just saw this extra overhead and possible error as a potential negative worth mentioning; at the least, this is probably the reason why the modules are not explicitly named already.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
