### ISSUE TITLE
deactivateItem initiates a second composition when canDeactivateItem resolves to false

### ISSUE THREAD

**Issue by schwuppdiwupp** [BlueSpire/Durandal#662]
I noticed that when deactivate() is called on an activator and the internal canDeactivateItem() resolves to false the code notifies all subscribers. This leads to a second call of attached() on every subscriber.

Also, in activate.js all calls to notifySubscribers() are wrapped in a condition (if (viaSetter)), except the one in computed.deactivateItem() is not. Is this intentional?

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
