### ISSUE TITLE
Add a method to http.js to enable beforeSend callback

### ISSUE THREAD

**Issue by kye** [BlueSpire/Durandal#663]
I would like to specify a beforeSend callback on an ajax post. Because $.post does not accept this parameter I'd like to add a ajax method to the plugin.

        ajax: function (method, url, data, headers, beforeSend) {
            return $.ajax({
                url: url,
                data: this.toJSON(data),
                type: method,
                contentType: 'application/json',
                dataType: 'json',
                headers: ko.toJS(headers),
                beforeSend: beforeSend
            });
        },

**Comment by davismj** [comment]
I'm not sure this is the best approach for a number of reasons. First of all, specifying 'dataType: json' on a DELETE request doesn't work (usually?). For this and other reasons, I will go ahead and make the change. I will create an ajax function which accepts a general [jQuery settings object](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings) and does some preprocessing on the object in line with knockout functions. In that way, the ajax method will parallel the get and post methods, allowing general XHRs.

**Comment by kye** [comment]
Thank you @davismj. That will meet the requirement.
