### ISSUE TITLE
observable plugin: UI fails to update after reassigning observable array

### ISSUE THREAD

**Issue by navels** [BlueSpire/Durandal#666]
Generally speaking, if x and y are observables in Durandal (i.e., knockout observables hidden behind ES5 getters and setters), then when you write

```
x = y;
```

what happens under the hood is that the underlying value of x is set equal to the underlying value of y, but x retains all the rest of its observable "baggage", i.e., subscriptions and whatnot.

The same thing is supposed to apply to observable arrays, but I've run into a bug.  Assume x and y are observable arrays, then, with underlying arrays _x and _y.  When y is made to be observable (via convertObject, either explicitly or by the binder), the plugin defines a bunch of array functions on _y that wrap the normal array functions.  For example (paraphrased from the code):

```
y_.pop = function() {
    y.valueWillMutate();
    var result = Array.prototype.pop.apply(y_);
    y.valueHasMutated();
    return result;
}
```

Then when you write

```
y.pop()
```

the getter for y returns y_, so you get

```
y_.pop()
```

and the wrapped array function will ensure that the appropriate notifications go out.

So far so good.  But the problem occurs when you assign x to y:

```
x = y;
```

Because the array function wrappers are on the underlying value y_, they get brought over to x.  Subsequent calls to those functions will call `y.valueWillMutate()`, etc., instead of `x.valueWillMutate()`.

Here is a fiddle showing the problem: http://navels.github.io/dFiddle-2.0/#extras/observableArray/index

I have a patch that rewrites the array functions every time the underlying array is accessed but that isn't really right, either.  You somehow want to keep track of all observables which have that underlying array so you can notify them all when the array changes.

For now we are just going to copy the array:

```
x = y.slice();
```

I guess the bottom-line is: you cannot have two observable arrays which share the same underlying array.  Works in pure knockout, but not the observable plugin.

**Comment by mryellow** [comment]
Ran into this one recently... my approach to work-around was something like:

```
observable(x).valueWillMutate();
x = y;
observable(x).valueHasMutated();
```

**Comment by navels** [comment]
I'm thinking that making x a computed observable that wraps y is probably the best workaround:

    get x() {
      return y;
    }

That fixes the dFiddle, or rather this does (the arrays in that example are x.arr and y.arr):

    get x() {
      return {
        arr: this.y.arr
      };
    }

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
