### ISSUE TITLE
Docs: Observable plugin, hasChanged signature undocumented

### ISSUE THREAD

**Issue by mryellow** [BlueSpire/Durandal#668]
`convertObject` and `convertProperty`, `hasChanged` property in signature didn't make it into inline docs. 

Accepts an array of functions.

https://github.com/BlueSpire/Durandal/blob/14ace8942395a017558b24331d89b24e355ae65e/src/plugins/js/observable.js#L162

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
