### ISSUE TITLE
Question on routes and page composition

### ISSUE THREAD

**Issue by mfromin** [BlueSpire/Durandal#669]
I have a simple app (based on the starter app) with three routes.

1 - Home page (list of articles)
2 - View article page
3 - Edit article page

The first time I visit the Edit Article page I fetch JSON from the server, populate a view model and then render the page. I have a binding handler that implements a rich text editor and the valueAccessor is the model data.  So far so good!

I then click back to the home page and then click again to edit a different article.  This time the valueAccessor shows empty/null so when the article loads the rich text editor is empty.  If I just refresh the page (CMD+R) the data for the binding hander magically appears 100% of the time.  

I am somewhat lost as to what might be happening when I return to a view that has already been loaded/rendered that would cause this to fail.  Is there some setting that forces each visit to a route to act like the route's data has never been loaded before?

I am happy to share code if needed.

**Comment by navels** [comment]
Check this out:

http://stackoverflow.com/questions/22503570/durandal-rebind-when-navigating-to-same-module-and-view-with-different-data

**Comment by mfromin** [comment]
Thank you for that - exactly where in the Durandal sample app does that code go?  In the main.js?  shell.js?  

Apologies for the newbie question ... I am trying to convert an Angular app to Durandal so I am new to the framework.

**Comment by explorer2309** [comment]
The activate function in your view model should get called on every load. And it should get the parameter to load the data appropriately. Can you create a sample code with your problem?

**Comment by mfromin** [comment]
So I have this code for a module:

define(['knockout', 'plugins/router'], function(ko, router) {
    return {
        sampleObservable: ko.observable('Sample text'),
        post: {
            test: "test content"
        },
        activate: function () {
            var self = this;
            var postId = router.activeInstruction().params[0];
            var apiURL = "http://localhost:8080/api/posts/" + postId;
            jQuery.getJSON(apiURL).done(function (data) {
                self.post.fullContent = ko.observable(data.fullContent);
                self.post.teaserContent = ko.observable(data.teaserContent);
                self.post.imageURL = ko.observable(data.imageURL);
                self.post.tags = ko.observable(data.tags);
                self.post.author = ko.observable(data.author);
                self.post.title = ko.observable(data.title);
                self.post.category = {
                    "_id": ko.observable(data.category._id)
                }
            });
        }
    }
});

If I manually enter a URL (e.g. http://localhost:63342/blog-durandal/index.html#test/554e42abfc39155705000001) Then I can see the post in the $data object for the HTML page.  

If I then go to the URL in the browser and manually type a different item URL (e.g. http://localhost:63342/blog-durandal/index.html#test/554fbdf38a0862294061a141) I see the page refresh (I see that activate runs again etc) but the post item in the debug does not change.  

I have this at the bottom of the HTML page to show me the current values:

<h3>Debug</h3>
<p><strong>$data</strong></p>
<pre data-bind="text: ko.toJSON($data, null, 2)"></pre>

The $data is NOT changing when I enter the second URL.  Oddly if I CMD+R in Chrome then I do get the correct data in the debug.  It is like once the data is fetched its not re-populating the observable properly.

**Comment by navels** [comment]
Are you *sure* that activate is being called both tiems?

But anyway, you should use a parameterized route and pull the post id into the activate method as a parameter.  For example:

http://stackoverflow.com/questions/24572515/durandal-routing-with-parameters

**Comment by mfromin** [comment]
I think I have this figured out...

When I fetch data using the activate() function I was not returning a promise from the jQuery call.  Now that I am doing that all seems to be working as I expected.

Something in one of the aforementioned StackOvervflow articles triggered this epiphany.  

I appreciate all of your help!

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
