### ISSUE TITLE
The hasFocus binding does not work for inputs on an animated dialog (Durandal 2.1, Knockout 3.3)

### ISSUE THREAD

**Issue by ctaleck** [BlueSpire/Durandal#672]
I am using the hasFocus binding in the composition lifecycle:

```
composition.addBindingHandler('hasFocus');
```

This trouble began after updating from Durandal 2.0 to 2.1 and Knockout 2.3 to 3.3. Knockout 3.3 turned hasFocus into a two-way binding and is causing the timing to be off-sync with the opening of a dialog with animation. Using the hasFocus binding works on a normally composed page.

Is there a way to delay the timing of the binding even more after the composition life-cycle?

**Comment by ctaleck** [comment]
My solution involves adding a timing delay.

https://gist.github.com/ctaleck/4e1ebf1c0fbc137d2672#file-bindinghandlers-js

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
