### ISSUE TITLE
CompositionComplete callbacks are not called in case of an error

### ISSUE THREAD

**Issue by jkanczler** [BlueSpire/Durandal#673]
Composition callbacks are called by the composition module when the composition count reaches 0 value and there's no error. It's wrong because: If you have multiple views on a page and just one of the views is failing then the composition callbacks are called randomly. It depends on the process, if the view that is failing processed last, then callbacks won't be called, but if the other views are processed last, then composition callback will be called.

On the other hand the router plugin depends on the composition callback as well. If the composition callback is not called, then the router stays in processing and you can't navigate to other page.

**Comment by jkanczler** [comment]
Oh, and actually if there's an error in a composition callback, then the compositionCount will be decreased to -1, because the onError will call the EndComposition again.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
