### ISSUE TITLE
Dialog show then promise never fires in IE9.

### ISSUE THREAD

**Issue by gsperry** [BlueSpire/Durandal#678]
dialog.show(model),then(function(){});

The then promise never fires in IE9.

**Comment by gsperry** [comment]
Waiting to removeHost and delete Instance.__dialog__ until after resolve is called does allow the promise to fire, but I do not know if this will cause undesired behavior in complex promise implementations where the dialog is assumed to be gone.

I have a functioning branch. All tests pass and I have verified no ill effects in IE9, 10, 11, and Chrome 46.

**Comment by gsperry** [comment]
Having thought about this, I will not submit a pull request. While this fix may work for me, I believe it to be poor form to conduct any business after the resolution of a promise.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
