### ISSUE TITLE
Incomplete handling of url manipulation/ browser back when isProcessing() is true

### ISSUE THREAD

**Issue by bleuetnoir** [BlueSpire/Durandal#682]
Hello,

   I have a basic form page. If the user click back (browser button, contextual menu) or another link, we display a confirmation message in canDeactivate so that the user have a last chance to stay in screen and save the changes. Common scenario.

  The problem is that it is still possible to use back or manipulation url in browser adress bar while the dialog is open (async process / promise in canDeactivate). I have tried to fix the problem in dequeueInstruction with something like that :

```
    function dequeueInstruction() {
        if (isProcessing()) {
            if (lastProcessingInstruction !== null) {
                router.activeInstruction(lastProcessingInstruction);
                var lastProcessingUrl = reconstructUrl(lastProcessingInstruction);
                router.navigate(lastProcessingUrl, false);
```

It doesn't work so well (depending on how is resolved canDeactivate and the number of time back was clicked) and the probleme is basically a desynchronisation of displayed url and active module.

It looks like the it should be trapped ealier but router isProcessing state is not visible fromhistory.js

Any suggestion on how to patch this problem?

Thanks in advance.

Eric

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
