### ISSUE TITLE
Dialog is not shown in case of an error

### ISSUE THREAD

**Issue by pinghuynh** [BlueSpire/Durandal#683]
Hello,

This may relate to issue #673, but after I applied fixes of #673, the problem still happens.

I use 'plugins/dialog' to show the popups on my page.
Example: dialog.show(new MyDialogModal());

The problem is: the dialog is not shown if the previous one got an error

How to reproduce this problem:
- Open dialog A
  - Call "dialog.show(new MyDialogModal())"
  - When it still has not been shown (compositionComplete still has not been called), disconnect the network (on Firefox, use File -> Work offline or Alt-F-K as hotkey)
  - Dialog A will never been displayed.
- Reconnect the network (uncheck Work offline)
- Open other dialogs, or dialog A itself
  -> They will also never been displayed. This is issue point.

Any suggestion on how to patch this problem?

Thanks in advance.

**Comment by pinghuynh** [comment]
Please try this issue on http://durandaljs.com/samples.html#modal

**Comment by jmvtrinidad** [comment]
Hi,

The error is from loading customModal.html.
The required html for customModal.js has not been loaded.
To ensure that the html required is already loaded, you can add it as a dependency for customModal.js.
Something like this.
```
define(['plugins/dialog', 'knockout', 'text!./customModal.html'], function (dialog, ko) {
    var CustomModal = function() {
        this.input = ko.observable('');
    };

    CustomModal.prototype.ok = function() {
        dialog.close(this, this.input());
    };

    CustomModal.prototype.canDeactivate = function () {
        return dialog.showMessage('Are you sure that\'s your favorite color?', 'Just Checking...', ['Yes', 'No']);
    };

    CustomModal.show = function(){
        return dialog.show(new CustomModal());
    };

    return CustomModal;
});
```

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
