### ISSUE TITLE
Events stop firing when listener is outside of `router`-composed area (WORKAROUND)

### ISSUE THREAD

**Issue by leftclickben** [BlueSpire/Durandal#686]
## Background

I have a `shell.html` that looks (stripped down) like this:

```
<div data-bind="widget: { kind: 'authentication' }"></div>
<div data-bind="router: {}"></div>
```

The `AuthenticationWidget` listens for an event that I am firing from another module, `UserService`.

This is the relevant code in `UserService`:

```
events.includeIn(this);
//...
this.login = function (credentials) {
    // send ajax request, then on success...
    this.trigger('authentication:logged-in', user);
}
```

This is the relevant code in `AuthenticationWidget.js` that does not work:

```
var loggedInUser = ko.observable();
this.shouldShowLoginButton = ko.computed(function () {
    return !loggedInUser();
});
this.activate = function () {
    var service = // get `UserService` instance from DI container
    loggedInSubscription = service.on('authentication:logged-in', function (user) {
        loggedInUser(user);
    });
};
this.login = function () {
    // Call the `login` method of `UserService`.
};
```

Then in `AuthenticationWidget.html` I have something like:

```
<!-- ko if: shouldShowLoginButton -->
<a data-bind="click: login">Login</a>
<!-- /ko -->
```
## Problem

If I load a page and login, it works correctly.  The login button disappears after the login is successful.

If I load a page, then navigate to another page, then login on that second page, the login is successful (as I can see in other parts of my application) but the login button does not disappear.  The `loggedInUser` observable is never updated, because although the event is fired, it is never received by the `AuthenticationWidget` that lies outside of the `router` binding.

It also works correctly if the `AuthenticationWidget` is placed somewhere inside the `router` binding, i.e. in the "main" part of the page.  But of course, that's not what I want because it is present in the header on every page.
## Workaround

I don't fully understand this, but looking at the code in `event.js` there are two ways of using the subscriptions, callback and promise.  The callback style is used above and does not work, but by switching to the promise style, it works.  The `AuthenticationWidget.activate` function becomes:

```
loggedInSubscription = service.on('authentication:logged-in').then(function (user) {
    loggedInUser(user);
});
```

(Instead of passing the function as a callback to `on` as above, I'm calling `on` and then calling `then` on the object that it passes back when there isn't a callback).

Like I said, I don't fully understand this, and I don't really have time to look further, I'm just posting this in case someone else has the same problem, to save them an hour or three :-)

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
