### ISSUE TITLE
knockout components in a view breaks in IE7.

### ISSUE THREAD

**Issue by jbaez** [BlueSpire/Durandal#688]
Using the latest Durandal from the master branch, knockout 3.3.0 (also tried with 3.4.0) and jQuery 1.8.0.
Defining a component like:

``` javascript
define('test-component', ['knockout'], function(ko) {
    ko.components.register('test-component', {
        viewModel: function(params) {
            this.componentValue = params.value;
        },
        template: '<span>test component</span>'
    });
});
```

And using it in a view like:

```
<test-component params="value: anObservable"></test-component>
```

Breaks in IE7 with the message: Unexpected call to method or property access.

**Comment by jbaez** [comment]
Just found out that It does work even in IE7 If the component is used in the view like: 
```
<div data-bind="component: { name: 'test-component', params: { value: anObservable } }"></div>
```

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
