### ISSUE TITLE
Dialog currentZIndex Incrementing

### ISSUE THREAD

**Issue by someyoungideas** [BlueSpire/Durandal#694]
Should the `currntZIndex` ever be reset after a dialog is closed? I encountered an issue where I created a custom dialog that uses the `getNextZIndex` function to set the z-index appropriately. Unfortunately, there are elements with static z-index from CSS in the modal. After the dialog has been opened over and over the dialog z-index is above the elements inside due to the `currentZIndex` incrementing.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
