### ISSUE TITLE
Dialog throws error on load with jquery 3.x

### ISSUE THREAD

**Issue by mattyas** [BlueSpire/Durandal#695]
in dialog.js
`loadables.load(function () {
                setDialogPosition(child, theDialog);
            });
`

should be replaced with 

`loadables.on("load", function () {
                setDialogPosition(child, theDialog);
            });
`

to be compatible with jquery 3.x
https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed

**Comment by davismj** [comment]
@mattyas We'd love a pull request! :smile:

**Comment by mattyas** [comment]
@davismj https://github.com/BlueSpire/Durandal/pull/696 submited

**Comment by jeffgarretson** [comment]
Rob, any chance of getting the NuGet package updated to include this fix? This is the last thing keeping me from updating to jQuery 3.x.

**Comment by EisenbergEffect** [comment]
Do we have a pull request for this?

**Comment by mattyas** [comment]
You have already accepted my pull request, but the NuGet package has not been updated since September 3 2016. Therefor the fix is not available for those who pulls it from NuGet.
