### ISSUE TITLE
Knockout 4.0 alpha compatibility tests

### ISSUE THREAD

**Issue by brianmhunt** [BlueSpire/Durandal#697]
Hi folks,

A Knockout 4.0 beta is on the horizon, being a substantial rewrite – mostly to divide Knockout into discrete ES6 import/exports.  You can have a look at the "umbrella" project here https://github.com/knockout/tko (TKO is an experimental fork intended to become KO 4.0).

TKO is still in alpha, with lots to do, but I think we're at a good place to touch base with major projects relying on knockout so we get feedback and can put together a straighforward upgrade-path.

The full changelog between KO3 and TKO is here: https://github.com/knockout/tko/blob/master/CHANGELOG.md – lots to be done (especially documentation, though KO 4 will be substantially compatible with knockout 3)

You can try it out with `npm install knockout/tko`, which will get the `master` branch.  In the `dist/` directory there are two files, `tko.js` and `ko.js`, the only difference being that `tko.js` exports a global `tko`, and `ko.js` exports the traditional `ko`.

If you get to testing it out, please feel free to issue bugs on the respective `tko.*` packages or `tko` package.  Also, please share there's a major feature, functionality, or capability that's missing.

Public discussion is at https://gitter.im/knockout/tko

Cheers

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
