### ISSUE TITLE
Custom transitions violate the Open Closed Principle

### ISSUE THREAD

**Issue by sethlivingston** [BlueSpire/Durandal#701]
Having to add custom transitions to the Durandal tree, rather than being able to keep them in our own app tree, violates the Open Closed Principle. It's particularly troublesome for us because we install Durandal using NPM, so we have to add transitions to the ./node_modules folder.

Please correct me if there's a way to add transitions without putting them in the durandal/transitions folder, and I just missed it.

**Comment by navels** [comment]
From the docs:
>Note: Transitions are expected to be located in a transitions folder under the durandal folder as stated above. However, you can easily change this conventional location. To do so either use RequireJS path configuration or override the compose module's convertTransitionToModuleId function.
