### ISSUE TITLE
Add a package.json

### ISSUE THREAD

**Issue by daedalus28** [BlueSpire/Durandal#702]
Npm can install directly from github, but _only_ if there is a package.json file. Since you closed the [issue on durandal-bower](https://github.com/BlueSpire/Durandal-Bower/issues/7), and durandal-bower doesn't have the recent fixes, can you just add a package.json file here? And if not, then can you update the durandal-bower repo?

**Comment by daedalus28** [comment]
I'm not clear why there are separate repos but this

**Comment by EisenbergEffect** [comment]
If you PR the package.json file, I will merge it in.

**Comment by daedalus28** [comment]
PR #703 should do it

**Comment by EisenbergEffect** [comment]
Merged.
