### ISSUE TITLE
Attempt to decorate http.post

### ISSUE THREAD

**Issue by Rus-iZet** [BlueSpire/Durandal#705]
Hi, i'm trying to decorate the function http.post a simple method:

```
var httppost = myDecorator(http.post);

var myDecorator= function (f) {
        return function () {
            // some code

            var result = f.apply(this, arguments);

            // again some code
            return result;
        }
    };
```

But every browser is display the same error:
   _TypeError: this.toJSON is not a function_

In the http.js file at the 102 line i replaced next code:
`data: this.toJSON(data),`
on
`data: JSON.stringify(data),`

and the error is gone.

What is the difference between the two methods? Is it possible to use the standard function in this method?

**Comment by navels** [comment]
toJSON is a method on the http module.  when this.toJSON is called, the "this" is the http module object.  later when your decorator calls f.apply, it is passing in a different "this" object.

instead:
```javascript
var httppost = myDecorator(http.post.bind(http));
```
