### ISSUE TITLE
[Website] Getting Started page is outdated

### ISSUE THREAD

**Issue by jpaugh** [BlueSpire/Durandal#706]
The [Getting Started] page on the website has an outdated dependency for Knockout. The source text of main.js on that page lists knockout-2.3.0.js as a dependency; but the HTML Starter Kit currently uses 3.4.0. 

Also, the `ul` nav in shell.js (second version) needs the `navbar-nav` class, in order to allow the nav links to stack horizontally, rather than vertically. (I'm guessing this is as a result of upgrading from Bootstrap 2 to Bootstrap 3; this is the only change needed to work well.)

[Getting Started]: http://durandaljs.com/get-started.html

**Comment by yanime** [comment]
As this framework is not maintained anymore I would suggest the getting started page to be removed, I see no reason to start a new project with durandal when there are plenty of other modern js frameworks

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
