### ISSUE TITLE
Mobile browser address bar does not hide when scrolling down (ios, chrome)

### ISSUE THREAD

**Issue by jimwards17** [BlueSpire/Durandal#707]
EDIT: simply open the microsoft.net samples solution and view in chrome on ios (not ipad). Chrome address bar is always present regardless of page length and scroll position. (this is also true for safari and firefox)

Is this intentional? What can I do to have the browser address bar hide as the page is scrolled down? This is valuable screen real estate. 

/***************************/
Using the durandal starter kit for the Microsoft.net platform. 

Using chrome on ios:

On initial load address bar will hide when scrolling down - navigate to a view within a child router - you will see that the chrome address bar remains on the screen even when scrolling down 

If page is refreshed chrome address bar will hide- navigate back to home view - address bar stuck on screen again.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
