### ISSUE TITLE
how could i build two shell page

### ISSUE THREAD

**Issue by lancer07** [BlueSpire/Durandal#708]
my block is i need a login page, but i am not sure how i could build the page.

**Comment by lancer07** [comment]
my issue is like that, is it true ?

// in main.js , after app.start()

if(isLogin){
       app.setRoot('viewmodels/shell', 'entrance');
}else{
       app.setRoot('viewmodels/pages/login', 'entrance');
}

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
