### ISSUE TITLE
endComposition method is decreasing the compositionCount onError

### ISSUE THREAD

**Issue by usmanaridian** [BlueSpire/Durandal#709]
While working on a bug where one of our viewModel's composition complete was not being called, I came to know that there was a javascript error was occurring (which I  am still trying to find) and that error triggered the onError of composition.js which in turn triggered the endComposition method. Where we are doing minus one on compositionCount variable. And by some how compositionCount value got into negative ,which was preventing the compositionCompleteCallbacks to execute.

I was thinking that it would be better we have a check that if compositionCount is already 0, don't decrements the value and leave it as 0.  I was thinking to make this change to the file and use in our project, but we are not allowed to make the changes to third party libraries.

So, I am suggesting this change to be made in the library. If not can you please share the reasoning to not implement this check.

Thanks

` function onError(context, error, element) {
        try {
            if (context.onError) {
                try {
                    context.onError(error, element);
                } catch (e) {
                    system.error(e);
                }
            } else {
                system.error(error);
            }
        } finally {
            endComposition(context, element, true);
        }
    }

    function endComposition(context, element, error) {

// this should check that compositionCount should not go to negative.
        compositionCount--;

        if(compositionCount === 0) {
            var callBacks = compositionCompleteCallbacks;
            compositionCompleteCallbacks = [];
            
            if (!error) {
                setTimeout(function () {
                    var i = callBacks.length;

                    while (i--) {
                        try {
                            callBacks[i]();
                        } catch (e) {
                            onError(context, e, element);
                        }
                    }
                }, 1);
            }
        }

        cleanUp(context);
    }
`

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
