### ISSUE TITLE
Incomplete cleanup of composed views when parent is detached before complete loading

### ISSUE THREAD

**Issue by decden** [BlueSpire/Durandal#711]
In the case of nested compositions, a composed view is not properly cleaned up if the parent is detached before the view has been attached.

The reason for this is that the knockout dispose callbacks added by the `triggerAttach` function will not be called. Since the parent of the newly attached view has just been detached, nobody will take care of cleaning the now detached DOM tree.

Note that this bug only generally happens if a view is composed and then immediately replaced or removed (before it has been loaded completely).

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
