### ISSUE TITLE
Malformed URL triggers an unhandled exception and mapUnknownRoutes is never called

### ISSUE THREAD

**Issue by Syltty** [BlueSpire/Durandal#713]
Hi,

If a user try to access a page with some dummy route parameters like 
> http://bla/login/%

Then `createParams` method (of /src/plugins/js/router.js) / `decodeURIComponent` is called with "%" parameter and crashes: "`Uncaught URIError: URI malformed`". `mapUnknownRoutes` is never called because this error is not handled. 

durandal version: 2.1.0

**Comment by Syltty** [comment]
I have a fix if you confirm it's a bug.

**Comment by EisenbergEffect** [comment]
Closing since Durandal has been superseded by Aurelia just shy of four years ago.
